# Generated by Django 3.0.6 on 2020-05-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/user/photo')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='images/user/photo')),
            ],
        ),
        migrations.RemoveField(
            model_name='shopuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shopuserrole',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='address',
            name='profile',
        ),
    ]
