# Generated by Django 3.0.6 on 2020-05-11 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopuser', '0003_auto_20200511_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='shopuser.Customer'),
            preserve_default=False,
        ),
    ]
