# Generated by Django 3.0.6 on 2020-05-11 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200511_1338'),
        ('shopuser', '0004_address_profile'),
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('price', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_products', to='shop.ProductVersion')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_sellers', to='shopuser.Seller')),
            ],
        ),
    ]
