# Generated by Django 3.0.6 on 2020-05-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_storageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageproduct',
            name='availability',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
