# Generated by Django 3.0.6 on 2020-05-11 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200511_1620'),
        ('storage', '0004_auto_20200511_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_products', to='shop.ProductVersion'),
        ),
    ]
