# Generated by Django 3.0.6 on 2020-05-13 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopuser', '0004_address_profile'),
        ('storage', '0005_auto_20200511_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storageproduct',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_products', to='shopuser.Seller'),
        ),
    ]
