# Generated by Django 3.0.6 on 2020-05-15 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200511_1620'),
        ('storage', '0006_auto_20200513_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='storageproduct',
            name='categories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='storage_products', to='shop.Category'),
            preserve_default=False,
        ),
    ]
