# Generated by Django 3.0.6 on 2020-05-16 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_storageproduct_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricesStory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices_story', to='storage.StorageProduct')),
            ],
        ),
    ]
