# Generated by Django 3.0.6 on 2020-05-16 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_pricesstory'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricesstory',
            name='storage_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prices_story', to='storage.StorageProduct'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricesstory',
            name='price',
            field=models.FloatField(),
        ),
    ]
