# Generated by Django 3.0.6 on 2020-05-16 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_auto_20200516_1515'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricesStory',
        ),
    ]
