# Generated by Django 3.0.6 on 2020-05-11 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200511_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productversion',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='count',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='price',
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='sellers',
        ),
    ]
