# Generated by Django 3.0.6 on 2020-05-11 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('office', '0001_initial'),
        ('shopuser', '0002_auto_20200511_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='seller',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='office', to='shopuser.Seller'),
        ),
    ]
