# Generated by Django 3.0.6 on 2020-05-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_auto_20200511_1723'),
        ('orders', '0003_sale_saleitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitems',
            name='storage_product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='storage.StorageProduct'),
            preserve_default=False,
        ),
    ]
