# Generated by Django 3.0.6 on 2020-05-13 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopuser', '0004_address_profile'),
        ('orders', '0004_auto_20200513_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='shopuser.Seller'),
            preserve_default=False,
        ),
    ]
