# Generated by Django 3.0.6 on 2020-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200513_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_average_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
